[theme]
primaryColor = "#3B82F6"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E293B"
font = "Inter"

[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[ui]
hideTopBar = true
hideSidebarNav = true
